#!/bin/bash
. "$(dirname $BASH_SOURCE)/_bootstrap.sh"


docker ps --quiet --all | \
    xargs --no-run-if-empty docker rm --force --volumes >> /dev/null

docker system prune --force

docker images | egrep '(weeks|months|years) ago' | awk '{ print $3 }' | \
    xargs --no-run-if-empty docker rmi --force >> /dev/null
