#!/bin/bash
. "$(dirname $BASH_SOURCE)/_bootstrap.sh"


if [[ $# > 2 ]]; then
    echo "Usage: ${0##*/} [TAG_PREFIX [REMOTE_NAME]]" >&2
    exit 1
fi

GIT_TAG_PREFIX="${1:-}"
GIT_REMOTE_NAME="${2:-"origin"}"

GIT_TAG="${GIT_TAG_PREFIX}$(TZ=":UTC" date '+%y%m%d%H%M%S')"
git tag "${GIT_TAG}"
git push "${GIT_REMOTE_NAME}" "refs/tags/${GIT_TAG}"
