#!/bin/bash
. "$(dirname $BASH_SOURCE)/_bootstrap.sh"


# ===== Constants and functions


function does_s3_object_exist {
    local s3_object_url="$1"

    aws s3 ls "${s3_object_url}" >> /dev/null
}


function create_s3_object {
    local s3_object_url="$1"

    echo '' | aws s3 cp - "${S3_OBJECT_URL}" >> /dev/null
}


# ===== Main


if [[ $# != 1 ]]; then
    error_out 1 "Usage: ${0##*/} S3_OBJECT_URL"
fi
S3_OBJECT_URL="$1"

if ! does_s3_object_exist "${S3_OBJECT_URL}"; then
    create_s3_object "${S3_OBJECT_URL}"
fi
