#!/bin/bash
. "$(dirname $BASH_SOURCE)/_bootstrap.sh"


# ===== Constants and functions


function tf_plan {
    local subcommand="$1"
    local plan_path="$2"
    local extra_args="$3"

    local args="${extra_args} -out=${plan_path}"
    if [[ "${subcommand}" == "destroy" ]]; then
        args="-destroy ${args}"
    fi

    terraform plan ${args}
}


function tf_apply {
    local subcommand="$1"
    local plan_path="$2"
    local extra_args="$3"

    terraform "${subcommand}" ${extra_args} "${plan_path}"
}


function main {
    local subcommand="$1"
    local args="${@:2}"

    local plan_path="$(mktemp)"
    trap "rm '${plan_path}'" INT TERM EXIT

    tf_plan "${subcommand}" "${plan_path}" "${args}"

    if [ -f "${plan_path}" ]; then
        read -p "Apply? Enter 'yes' to confirm: " confirmation
        if [[ "${confirmation,,}" == "yes" ]]; then
            tf_apply "${subcommand}" "${plan_path}" "${args}"
        fi
    fi
}


# ===== Main


if [[ $# == 0 ]] || ! [[ "$1" =~ ^(apply|destroy)$ ]]; then
    error_out 1 "Usage: ${0##*/} apply|destroy [ARGS...]" >&2
fi

main $@
